// META_PROGRAM: react.godot script. Do not remove this comment.  
using Godot;
using System;

public partial class Butt : Button, IReactable
{
    [ReactState]
    private State<bool> is_active;

    // Don't edit! Generated by meta programming. 
    private bool is_active_ { get => is_active.Get(police); set { is_active.Set(value); } } 
    private ReactPolice police;

	public override void _Ready()
    {
        police = new ReactPolice(this);
        is_active = new State<bool>(police, false);
    }

    public void React()
    {
        police.OnEnter();
        
        GD.Print("Butt react");

        SizeFlagsVertical = SizeFlags.ExpandFill;
        
        Text = is_active_ ? "Click: On" : "Click: Off";

        void toggle()
        {
            is_active_ = ! is_active_;
        }
        police.UseEffect(() => {
            Pressed += toggle;
            return () => {
                Pressed -= toggle;
            };
        });
        
        police.OnExit();
    }

    public void SetProps(
        // Don't edit! Generated by meta programming. 
        
    )
    {
        bool need_react = false;

        // Don't edit! Generated by meta programming. 
        

        if (need_react)
        {
            React();
        }
    }
}
