// META_PROGRAM: react.godot script. Do not remove this comment.  
using Godot;
using System;

public partial class Demo : MarginContainer, IReactable
{
    private State<int> n_buttons;

    private ReactPolice police;

	private Label label;
	private NBSlider nBSlider;
	private VBox vBox;

	public override void _Ready()
    {
        police = new ReactPolice(this);

        n_buttons = new State<int>(police, 3);

		label = GetNode<Label>("HBoxContainer/Label");
		nBSlider = GetNode<NBSlider>("HBoxContainer/NBSlider");
		vBox = GetNode<VBox>("HBoxContainer/VBox");

		Reactor.Init(this);
    }
	public override void _Process(double delta)
	{
		Reactor.OnNewFrame();
	}

    public void React()
    {
        police.OnEnter();
        
        GD.Print("Demo react");
        label.Text = n_buttons.Get(police).ToString();
        nBSlider.SetProps(n_buttons.Get(police), (double v) => {
            n_buttons.Set((int) v);
        });
        vBox.SetProps(n_buttons.Get(police));
        
        police.OnExit();
    }

    public void SetProps(
        // Don't edit! Generated by meta programming. 
        
	)
    {
        bool need_react = false;

        // Don't edit! Generated by meta programming. 
        
        if (need_react)
        {
            React();
        }
    }

    private int acc;
    public void OnTimer()
    {
        GD.Print("Time:", acc);
        acc ++;
    }
}
