// META_PROGRAM: react.godot script. Do not remove this comment.  
using Godot;
using System;

public partial class NBSlider : VSlider, IReactable
{
    [ReactProp]
    private int n_butt;
    [ReactProp]
    private ValueChangedEventHandler callback;

    // Don't edit! Generated by meta programming. 
    
    private ReactPolice police;

	public override void _Ready()
    {
        police = new ReactPolice(this);
    }

    public void React()
    {
        police.OnEnter();
        
        GD.Print("NBSlider react");
        Value = n_butt;
        police.UseEffect(() => {
            ValueChanged += callback;
            return () => {
                ValueChanged -= callback;
            };
        });
        
        police.OnExit();
    }

    public void SetProps(
        // Don't edit! Generated by meta programming. 
        int n_butt_, ValueChangedEventHandler callback_
    )
    {
        bool need_react = false;

        // Don't edit! Generated by meta programming. 
        if (n_butt != n_butt_) { n_butt = n_butt_; need_react = true; } if (callback != callback_) { callback = callback_; need_react = true; } 

        if (need_react)
        {
            React();
        }
    }
}
