// META_PROGRAM: react.godot script. Do not remove this comment.  
using Godot;
using System;

public partial class Demo : MarginContainer, IReactable
{
    private State<int> n_buttons;

    private ReactPolice police;

	private Label label;
	private NBSlider nBSlider;

	public override void _Ready()
    {
		Reactor.Init(this);
        police = new ReactPolice(this);
        n_buttons = new State<int>(police, 3);

		label = GetNode<Label>("HBoxContainer/Label");
		nBSlider = GetNode<NBSlider>("HBoxContainer/NBSlider");
    }
	public override void _Process(double delta)
	{
		Reactor.OnNewFrame();
	}

    public void React()
    {
        police.OnEnter();
        
        label.Text = n_buttons.Get().ToString();
        
        police.OnExit();
    }

    public void SetProps(
        // Don't edit! Generated by meta programming. 
        
	)
    {
        bool need_react = false;

        // Don't edit! Generated by meta programming. 
        
        if (need_react)
        {
            React();
        }
    }
}
